---
- hosts: all
  name: "Pull"
  remote_user: isucon
  vars_files:
    - "../vars/vars.yml"
  tasks:
    - name: "Pull"
      ansible.builtin.git:
        repo: "{{ github.repo_url }}"
        dest: "{{ project_root }}"
        version: "{{ deploy_branch }}"
        force: true

    - name: "Get last commit"
      ansible.builtin.command:
        cmd: "git log --pretty=oneline -n 1"
        chdir: "{{ project_root }}"
      register: last_commit
      changed_when: false

    - name: "Send last commit"
      ansible.builtin.uri:
        url: "{{ webhook_url }}"
        method: POST
        body_format: json
        body: '{"content": "**Deploying...**:\nbranch: `{{ deploy_branch }}`\ncommit: `{{ last_commit.stdout }}`"}'
        status_code:
          - 204
      changed_when: false

- hosts: all
  name: "Setup systemd conf"
  remote_user: isucon
  vars_files:
    - "../vars/vars.yml"
  tasks:
    - name: "Set systemd conf files"
      ansible.builtin.copy:
        remote_src: true
        src: "{{ systemd.conf_dir.repo }}/"
        dest: "{{ systemd.conf_dir.original }}"
        mode: "755"
      become: true

    - name: "Daemon reload"
      ansible.builtin.systemd:
        daemon_reload: true
      become: true


- hosts: all
  name: "Deploy app"
  remote_user: isucon
  vars_files:
    - "../vars/vars.yml"
  tasks:
    - name: "Build"
      ansible.builtin.command:
        cmd: "{{ go_path }} build -o {{ app.bin }}"
        chdir: "{{ app.dir }}"
      changed_when: false

    - name: "Restart app"
      ansible.builtin.systemd:
        name: "{{ app.service_name }}"
        state: restarted
        daemon_reload: true
      become: true